application: peaceful-web-500
version: 1
runtime: php
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /about
  static_dir: about

- url: /.*
  script: index.php
